#!/bin/bash
echo "🦅 Welcome to AbEthiopia Cyber Intelligence Platform"
echo "===================================================="
echo ""
echo "🇪🇹 Ethiopian-Powered Threat Intelligence"
echo ""
echo "🌐 Platform Access:"
echo "   🖥️  Threat Analyzer: http://localhost:8080"
echo "   📚 API Documentation: http://localhost:8000/api/docs"
echo "   📊 AbEthiopia Dashboard: http://localhost:3000"
echo "   👤 Username: abere"
echo "   🔑 Password: Sudo12"
echo ""
echo "🔧 Quick Commands:"
echo "   ./manage-platform.sh status"
echo "   ./abethiopia-platform.sh (this script)"
echo ""
echo "🎯 Developed with 🇪🇹 Pride"
